---
- name: Get all endpoints from Cisco ISE
  hosts: ise_servers
  gather_facts: no
  vars:
    ise_server: 'https://10.150.1.14'
    username: 'admin'
    password: 'Vmware@12345'
  tasks:
    - name: Get endpoints
      uri:
        url: "{{ ise_server }}/ers/config/endpoint"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: response

    - name: Print endpoints
      debug:
        var: response.json
...
